// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATFbHTtwX5aBY0bQb0cem0QlhnIz0VN30',
    appId: '1:435703719500:web:4ab15d974b30b0037ff6e9',
    messagingSenderId: '435703719500',
    projectId: 'clubes-deportivos-a07c9',
    authDomain: 'clubes-deportivos-a07c9.firebaseapp.com',
    storageBucket: 'clubes-deportivos-a07c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoIvLHZ5SQF2BxSHjuKE2thZtADUQd3lE',
    appId: '1:435703719500:android:ded342802832d2617ff6e9',
    messagingSenderId: '435703719500',
    projectId: 'clubes-deportivos-a07c9',
    storageBucket: 'clubes-deportivos-a07c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHwClIuwlsJW19SRIpQCYogZG3ZIlY5Kk',
    appId: '1:435703719500:ios:5b9d34501f6b2a897ff6e9',
    messagingSenderId: '435703719500',
    projectId: 'clubes-deportivos-a07c9',
    storageBucket: 'clubes-deportivos-a07c9.firebasestorage.app',
    iosBundleId: 'com.clubesdeportivos.app',
  );
}
