import '../../models/club/actividad.dart';
import '../../models/club/club_config.dart';
import '../../models/club/instalacion.dart';
import 'paletas_club.dart';

class ClubConfigActual {
  static const _horariosPistas = [
    '06:30',
    '08:00',
    '09:30',
    '11:00',
    '12:30',
    '14:00',
    '15:30',
    '17:00',
    '18:30',
    '20:00',
    '21:30',
  ];

  static const _preciosPistasCentimos = {
    '06:30': 1200,
    '08:00': 1200,
    '09:30': 1200,
    '11:00': 1200,
    '12:30': 1600,
    '14:00': 1600,
    '15:30': 1600,
    '17:00': 1600,
    '18:30': 2400,
    '20:00': 2400,
    '21:30': 2400,
  };

  static const ClubConfig config = ClubConfig(
    clubId: 'club-demo',
    zonaHoraria: 'Europe/Madrid',
    nombre: 'Club Deportivo Ejemplo',
    deporte: 'Deporte y bienestar',

    logo: 'assets/images/yo_reservo_logo.png',

    telefono: '900 000 000',
    email: 'info@clubdeportivoejemplo.es',

    direccion: 'Avenida del Deporte, 1\n00000 Ciudad',

    horario: 'Lunes a Domingo\n08:00 – 22:00',

    fondo: 'assets/images/gimnasio_real.jpg',

    // Cambiar solo esta selección aplica la paleta completa al club.
    paleta: PaletasClub.violeta,

    estilo: 'claro',

    hero: 'assets/images/padel_ia.png',
    imagenLogin: 'assets/images/gimnasio_real.jpg',
    menuIcon: 'menuRounded',

    imagenInstalaciones: 'assets/images/padel_real.jpg',
    imagenReservas: 'assets/images/padel_real.jpg',
    imagenInformacion: 'assets/images/padel_real.jpg',
    imagenBienvenida: 'assets/images/padel_real.jpg',

    imagenes: {},

    administradores: ['martin.bautista.sanchez@gmail.com'],

    modulos: {
      'reservations': true,
      'payments': false,
      'accessControl': false,
      'notifications': true,
      'matches': false,
      'ranking': false,
      'padelLevel': true,
    },

    instalaciones: [
      Instalacion(
        id: 'instalacion_deportiva_1',
        nombre: 'Pista deportiva de ejemplo',
        tipo: 'Instalación deportiva',
        descripcion: 'Instalación deportiva configurable por el cliente.',
        imagen: 'assets/images/padel_real.jpg',
        horarios: [
          '08:00',
          '09:30',
          '11:00',
          '12:30',
          '14:00',
          '15:30',
          '17:00',
          '18:30',
          '20:00',
          '21:30',
        ],
        duracionReservaMinutos: 90,
        normas: [
          'Las reservas tienen una duración de 1 hora y 30 minutos.',
          'Las reservas pueden cancelarse hasta 1 hora antes.',
          'Las reservas no son transferibles.',
        ],
        reservasActivas: true,
        pagosActivos: false,
        accesoDigitalActivo: false,
      ),
    ],

    actividades: [
      Actividad(
        id: 'padel',
        nombre: 'Pádel',
        tipo: 'Pádel',
        descripcion: 'Reserva de pistas de pádel.',
        imagen: 'assets/images/padel_ia.png',
        icono: 'sports_tennis',
        instalaciones: [
          Instalacion(
            id: 'pista_padel_1',
            nombre: 'Pista de Pádel 1',
            tipo: 'Pista de pádel',
            descripcion: 'Pista de pádel 1.',
            imagen: 'assets/images/padel_real.jpg',
            horarios: _horariosPistas,
            preciosPorHorarioCentimos: _preciosPistasCentimos,
            duracionReservaMinutos: 90,
            maxMinutosPorDia: 180,
            maxDiasAntelacion: 10,
            minutosAntelacionCancelacion: 60,
            normas: [
              'Las reservas tienen una duración de 1 hora y 30 minutos.',
              'Las reservas pueden cancelarse hasta 1 hora antes.',
              'Las reservas no son transferibles.',
            ],
            reservasActivas: true,
            pagosActivos: false,
            accesoDigitalActivo: false,
          ),
          Instalacion(
            id: 'pista_padel_2',
            nombre: 'Pista de Pádel 2',
            tipo: 'Pista de pádel',
            descripcion: 'Pista de pádel 2.',
            imagen: 'assets/images/padel_ia.png',
            horarios: _horariosPistas,
            preciosPorHorarioCentimos: _preciosPistasCentimos,
            duracionReservaMinutos: 90,
            maxMinutosPorDia: 180,
            maxDiasAntelacion: 10,
            minutosAntelacionCancelacion: 60,
            normas: [
              'Las reservas tienen una duración de 1 hora y 30 minutos.',
              'Las reservas pueden cancelarse hasta 1 hora antes.',
              'Las reservas no son transferibles.',
            ],
            reservasActivas: true,
            pagosActivos: false,
            accesoDigitalActivo: false,
          ),
          Instalacion(
            id: 'pista_padel_3',
            nombre: 'Pista de Pádel 3',
            tipo: 'Pista de pádel',
            descripcion: 'Pista de pádel 3.',
            imagen: 'assets/images/padel_ia.png',
            horarios: _horariosPistas,
            preciosPorHorarioCentimos: _preciosPistasCentimos,
            duracionReservaMinutos: 90,
            maxMinutosPorDia: 180,
            maxDiasAntelacion: 10,
            minutosAntelacionCancelacion: 60,
            normas: [
              'Las reservas tienen una duración de 1 hora y 30 minutos.',
              'Las reservas pueden cancelarse hasta 1 hora antes.',
              'Las reservas no son transferibles.',
            ],
            reservasActivas: true,
            pagosActivos: false,
            accesoDigitalActivo: false,
          ),
        ],
      ),

      Actividad(
        id: 'tenis',
        nombre: 'Tenis',
        tipo: 'Tenis',
        descripcion: 'Reserva de pistas de tenis.',
        imagen: 'assets/images/tenis_ia.png',
        icono: 'sports_tennis',
        instalaciones: [
          Instalacion(
            id: 'pista_tenis_1',
            nombre: 'Pista de Tenis 1',
            tipo: 'Pista de tenis',
            descripcion: 'Pista de tenis 1.',
            imagen: 'assets/images/tenis_ia.png',
            horarios: _horariosPistas,
            preciosPorHorarioCentimos: _preciosPistasCentimos,
            duracionReservaMinutos: 90,
            maxMinutosPorDia: 180,
            maxDiasAntelacion: 10,
            minutosAntelacionCancelacion: 60,
            normas: [
              'Las reservas tienen una duración de 1 hora y 30 minutos.',
              'Las reservas pueden cancelarse hasta 1 hora antes.',
            ],
            reservasActivas: true,
            pagosActivos: false,
            accesoDigitalActivo: false,
          ),
          Instalacion(
            id: 'pista_tenis_2',
            nombre: 'Pista de Tenis 2',
            tipo: 'Pista de tenis',
            descripcion: 'Pista de tenis 2.',
            imagen: 'assets/images/tenis_ia.png',
            horarios: _horariosPistas,
            preciosPorHorarioCentimos: _preciosPistasCentimos,
            duracionReservaMinutos: 90,
            maxMinutosPorDia: 180,
            maxDiasAntelacion: 10,
            minutosAntelacionCancelacion: 60,
            normas: [
              'Las reservas tienen una duración de 1 hora y 30 minutos.',
              'Las reservas pueden cancelarse hasta 1 hora antes.',
            ],
            reservasActivas: true,
            pagosActivos: false,
            accesoDigitalActivo: false,
          ),
        ],
      ),

      Actividad(
        id: 'gimnasio',
        nombre: 'Gimnasio',
        tipo: 'Gimnasio',
        descripcion: 'Clases y actividades dirigidas del gimnasio.',
        imagen: 'assets/images/gimnasio_ia.png',
        icono: 'fitness_center',
        instalaciones: [
          Instalacion(
            id: 'gimnasio_zumba',
            nombre: 'Zumba',
            tipo: 'Clase dirigida',
            descripcion: 'Clase dirigida de Zumba.',
            imagen: 'assets/images/gimnasio_real.jpg',
            horarios: ['09:00', '10:00', '17:00', '18:00', '19:00', '20:00'],
            duracionReservaMinutos: 60,
            maxMinutosPorDia: 60,
            maxDiasAntelacion: 10,
            minutosAntelacionCancelacion: 60,
            normas: [
              'La clase tiene una duración de 60 minutos.',
              'La reserva puede cancelarse hasta 1 hora antes.',
              'La reserva es personal y no transferible.',
            ],
            reservasActivas: true,
            pagosActivos: false,
            accesoDigitalActivo: false,
          ),
          Instalacion(
            id: 'gimnasio_spinning',
            nombre: 'Spinning',
            tipo: 'Clase dirigida',
            descripcion: 'Clase dirigida de Spinning.',
            imagen: 'assets/images/gimnasio_real_2.jpg',
            horarios: [
              '08:00',
              '09:00',
              '16:00',
              '17:00',
              '18:00',
              '19:00',
              '20:00',
            ],
            duracionReservaMinutos: 45,
            maxMinutosPorDia: 45,
            maxDiasAntelacion: 10,
            minutosAntelacionCancelacion: 60,
            normas: [
              'La clase tiene una duración de 45 minutos.',
              'La reserva puede cancelarse hasta 1 hora antes.',
              'La reserva es personal y no transferible.',
            ],
            reservasActivas: true,
            pagosActivos: false,
            accesoDigitalActivo: false,
          ),
          Instalacion(
            id: 'gimnasio_boxeo',
            nombre: 'Boxeo',
            tipo: 'Clase dirigida',
            descripcion: 'Clase dirigida de Boxeo.',
            imagen: 'assets/images/mancuernas.jpg',
            horarios: ['10:00', '11:00', '17:00', '18:00', '19:00', '20:00'],
            duracionReservaMinutos: 60,
            maxMinutosPorDia: 60,
            maxDiasAntelacion: 10,
            minutosAntelacionCancelacion: 60,
            normas: [
              'La clase tiene una duración de 60 minutos.',
              'La reserva puede cancelarse hasta 1 hora antes.',
              'La reserva es personal y no transferible.',
            ],
            reservasActivas: true,
            pagosActivos: false,
            accesoDigitalActivo: false,
          ),
        ],
      ),
    ],
  );
}
